### PR TITLE
HmtxTable Vector -> Array

### PR DESCRIPTION
**Pull request by jcxavier**
replaced the leftSideBearing vector with an array to prevent out-of-bounds crashes. it doesn't look like it's being used for anything anyway, so even a return 0; would do I guess

### CODE REVIEW

**Comment by track3r** [comment]
I saw this crash some time, If i'm not wrong it occurs when glyph is missing from font. Changing data structure instead of adding a check feels wrong to me

**Comment by catdawg** [comment]
the newline was creating the crash... maybe it tried to render the slash in \n ? and that isn't on the font...  Not sure how this actually works.

**Comment by jcxavier** [comment]
We can also replace it with a length check. I also had it before and it was working. The problem is that it crashes when going out of bounds.

**Comment by dejan-gd** [comment]
Looks good

**Pull request merged**
